server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: drone-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/drones/**

          - id: package-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/packages/**

          - id: route-service
            uri: http://localhost:8083
            predicates:
              - Path=/api/v1/routes/**

          - id: delivery-service
            uri: http://localhost:8084
            predicates:
              - Path=/api/v1/deliveries/**